import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { remark } from 'remark';
import remarkGfm from 'remark-gfm';
import html from 'remark-html';

const CONTENT_DIR = path.join(process.cwd(), 'content');
const POLICIES_DIR = path.join(CONTENT_DIR, 'policies');
const GENERATED_STATIC_OUTPUT_PATH = path.join(
	process.cwd(),
	'src',
	'generated',
	'static-content-data.ts'
);
const MD_EXTENSION_REGEX = /\.md$/i;

interface GeneratedStaticPage {
	contentHtml: string;
	description?: string;
	slug: string;
	title: string;
}

async function renderMarkdown(markdown: string): Promise<string> {
	const processedContent = await remark().use(remarkGfm).use(html).process(markdown);
	return processedContent.toString();
}

async function generateStaticCategoryData(
	categoryDirectory: string
): Promise<GeneratedStaticPage[]> {
	if (!fs.existsSync(categoryDirectory)) {
		return [];
	}

	const files = fs.readdirSync(categoryDirectory).filter((fileName) => fileName.endsWith('.md'));
	const generatedPages: GeneratedStaticPage[] = [];

	for (const fileName of files) {
		const slug = fileName.replace(MD_EXTENSION_REGEX, '');
		const fullPath = path.join(categoryDirectory, fileName);
		const fileContents = fs.readFileSync(fullPath, 'utf8');
		const { data, content } = matter(fileContents);
		const title = String(data.title ?? slug);
		const description = data.description ? String(data.description) : undefined;
		const hasDistinctDescription =
			description && description.trim().toLowerCase() !== title.trim().toLowerCase();
		const contentHtml = await renderMarkdown(content);

		generatedPages.push({
			slug,
			title,
			description: hasDistinctDescription ? description : undefined,
			contentHtml,
		});
	}

	return generatedPages;
}

async function generateStaticData(): Promise<void> {
	const policies = await generateStaticCategoryData(POLICIES_DIR);
	const staticFileContents = `/* eslint-disable */
// This file is auto-generated by scripts/generate_static_content_data.ts.
// Do not edit by hand.

export interface GeneratedStaticPage {
	contentHtml: string;
	description?: string;
	slug: string;
	title: string;
}

export const POLICIES: GeneratedStaticPage[] = ${JSON.stringify(policies, null, 2)};
`;

	await fs.promises.mkdir(path.dirname(GENERATED_STATIC_OUTPUT_PATH), { recursive: true });
	await fs.promises.writeFile(GENERATED_STATIC_OUTPUT_PATH, staticFileContents, 'utf8');
}

try {
	await generateStaticData();
	console.log('Generated static policy content data.');
} catch (error) {
	console.error('Failed to generate static policy content data.');
	throw error;
}
